server:
  port: 8091

# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# ChatGPT SDK Config
chatgpt:
  sdk:
    config:
      # 官网地址 https://api.openai.com/
      api-host: https://79e984a3423cc9a81cff6c315aace3c8.api-forwards.com/
      # 官网申请 https://platform.openai.com/account/api-keys
      api-key: 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
      # 自主申请 http://api.xfg.im:8080/authorize?username=xfg&password=123 - 有时效性，主要为了大家学习使用
#      auth-token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4ZmciLCJleHAiOjE2OTAwMzI5MDQsImlhdCI6MTY5MDAyOTMwNCwianRpIjoiOTBkNzc5NjYtOWM5MS00MGVmLWJmNjktNzYzNDljNmUyMDkyIiwidXNlcm5hbWUiOiJ4ZmcifQ.x7P6Rc249SgbxpqWhgKahYP8A8AllNI_26DV08a1AZs
wx:
  config:
    originalid: gh_3bbe530ed638
    appid: wx7cc0de005680424b
    token: b8b6
# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml